final Map<String, List<Map<String, dynamic>>> allExercises = {
  'back': [
    {'name': 'seated lower back stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/seated lower back stretch.gif'},
    {'name': 'standing lateral stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/standing lateral stretch.gif'},
    {'name': 'kneeling lat stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/kneeling lat stretch.gif'},
    {'name': 'lower back curl', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/lower back curl.gif'},
    {'name': 'one arm against wall', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/one arm against wall.gif'},
    {'name': 'side lying floor stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side lying floor stretch.gif'},
    {'name': 'sphinx', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/sphinx.gif'},
    {'name': 'spine stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/spine stretch.gif'},
    {'name': 'standing pelvic tilt', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/standing pelvic tilt.gif'},
    {'name': 'upper back stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/upper back stretch.gif'},
    {'name': 'upward facing dog', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/upward facing dog.gif'},
    {'name': 'two toe touch (male)', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/two toe touch (male).gif'},
  ],

  'chest': [
    {'name': 'clock push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.3, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/clock push-up.gif'},
    {'name': 'decline push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.35, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/decline push-up.gif'},
    {'name': 'incline push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.35, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/incline push-up.gif'},
    {'name': 'isometric wipers', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.02, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/isometric wipers.gif'},
    {'name': 'push-up (wall)', 'baseSetsReps': 2, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/push-up (wall).gif'},
    {'name': 'push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/push-up.gif'},
    {'name': 'shoulder tap push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/shoulder tap push-up.gif'},
    {'name': 'dynamic chest stretch (male)', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.02, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/dynamic chest stretch (male).gif'},
    {'name': 'isometric chest squeeze', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.02, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/isometric chest squeeze.gif'},
    {'name': 'wide hand push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/wide hand push-up.gif'},
    {'name': 'push and pull bodyweight', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/push and pull bodyweight.gif'},
    {'name': 'kneeling push-up (male)', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.35, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/kneeling push-up (male).gif'},
    {'name': 'archer push up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.5, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/archer push up.gif'},
  ],

  'cardio': [
    {'name': 'mountain climber', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/mountain climber.gif'},
    {'name': 'run', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/run.gif'},
    {'name': 'burpee', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.5, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/burpee.gif'},
    {'name': 'astride jumps (male)', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/astride jumps (male).gif'},
    {'name': 'half knee bends (male)', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/half knee bends (male).gif'},
    {'name': 'semi squat jump (male)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/semi squat jump (male).gif'},
    {'name': 'star jump (male)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/star jump (male).gif'},
    {'name': 'skater hops', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/skater hops.gif'},
    {'name': 'high knee against wall', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/high knee against wall.gif'},
    {'name': 'push to run', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/push to run.gif'},
  ],

  'lower arms':[
    {'name': 'side wrist pull stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side wrist pull stretch.gif'},
    {'name': 'modified push up to lower arms', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/modified push up to lower arms.gif'},
    {'name': 'wrist circles', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/wrist circles.gif'},
  ],
  'lower legs': [
    {'name': 'circles knee stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/circles knee stretch.gif'},
    {'name': 'ankle circles', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.4, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/ankle circles.gif'},
    {'name': 'bodyweight standing calf raise', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.5, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bodyweight standing calf raise.gif'},
    {'name': 'calf stretch with hands against wall', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/calf stretch with hands against wall.gif'},
    {'name': 'one leg floor calf raise', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.5, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/one leg floor calf raise.gif'},
    {'name': 'standing calves', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.5, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/standing calves.gif'},
    {'name': 'calf push stretch with hands against wall', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/calf push stretch with hands against wall.gif'},
    {'name': 'standing calf raise (on a staircase)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.5, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/standing calf raise (on a staircase).gif'},
  ],

  'neck': [
    {'name': 'side push neck stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side push neck stretch.gif'},
    {'name': 'neck side stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/neck side stretch.gif'},
  ],
  'shoulders': [
    {'name': 'rear deltoid stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/rear deltoid stretch.gif'},
    {'name': 'left hook. boxing', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/left hook. boxing.gif'},
  ],
  'upper arms': [
    {'name': 'body-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/body-up.gif'},
    {'name': 'close-grip push-up', 'baseSetsReps': 3, 'baseReps': 8, 'burnCalperRep': 0.75, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/close-grip push-up.gif'},
    {'name': 'diamond push-up', 'baseSetsReps': 3, 'baseReps': 6, 'burnCalperRep': 0.8, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/diamond push-up.gif'},
    {'name': 'overhead triceps stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/overhead triceps stretch.gif'},
    {'name': 'reverse dip', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/reverse dip.gif'},
    {'name': 'side push-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side push-up.gif'},
    {'name': 'triceps dips floor', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/triceps dips floor.gif'},
    {'name': 'triceps stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/triceps stretch.gif'},
    {'name': 'push-up on lower arms', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/push-up on lower arms.gif'},
    {'name': 'bodyweight side lying biceps curl', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bodyweight side lying biceps curl.gif'},
    {'name': 'biceps leg concentration curl', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/biceps leg concentration curl.gif'},
    {'name': 'bodyweight kneeling triceps extension', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bodyweight kneeling triceps extension.gif'},
    {'name': 'close-grip push-up (on knees)', 'baseSetsReps': 3, 'baseReps': 8, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/close-grip push-up (on knees).gif'},
    {'name': 'bench dip (knees bent)', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bench dip (knees bent).gif'},
  ],

  'upper legs': [
    {'name': 'jump squat', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.8, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/jump squat.gif'},
    {'name': 'kick out sit', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/kick out sit.gif'},
    {'name': 'lying (side) quads stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/lying (side) quads stretch.gif'},
    {'name': 'march sit (wall)', 'baseSetsSecs': 1, 'baseSecs': 30, 'burnCalperSec': 0.1, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/march sit (wall).gif'},
    {'name': 'rear decline bridge', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/rear decline bridge.gif'},
    {'name': 'side hip abduction', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side hip abduction.gif'},
    {'name': 'single leg platform slide', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/single leg platform slide.gif'},
    {'name': 'standing single leg curl', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/standing single leg curl.gif'},
    {'name': 'hug knees to chest', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/hug knees to chest.gif'},
    {'name': 'iron cross stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/iron cross stretch.gif'},
    {'name': 'pelvic tilt into bridge', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/pelvic tilt into bridge.gif'},
    {'name': 'seated glute stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/seated glute stretch.gif'},
    {'name': 'straight leg outer hip abductor', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/straight leg outer hip abductor.gif'},
    {'name': 'walking lunge', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/walking lunge.gif'},
    {'name': 'twist hip lift', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/twist hip lift.gif'},
    {'name': 'forward jump', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.85, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/forward jump.gif'},
    {'name': 'backward jump', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.85, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/backward jump.gif'},
    {'name': 'butterfly yoga pose', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/butterfly yoga pose.gif'},
    {'name': 'hamstring stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/hamstring stretch.gif'},
    {'name': 'all fours squat stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/all fours squat stretch.gif'},
    {'name': 'leg up hamstring stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/leg up hamstring stretch.gif'},
    {'name': 'runners stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/runners stretch.gif'},
    {'name': 'seated wide angle pose sequence', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/seated wide angle pose sequence.gif'},
    {'name': 'world greatest stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/world greatest stretch.gif'},
    {'name': 'squat to overhead reach', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.75, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/squat to overhead reach.gif'},
    {'name': 'side bridge hip abduction', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side bridge hip abduction.gif'},
    {'name': 'split squats', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.75, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/split squats.gif'},
    {'name': 'bodyweight drop jump squat', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.85, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bodyweight drop jump squat.gif'},
    {'name': 'quick feet v. 2', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.1, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/quick feet v. 2.gif'},
    {'name': 'lunge with jump', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.85, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/lunge with jump.gif'},
  ],

  'waist': [
    //{'name': '3/4 sit-up', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/3-4 sit-up.gif'},
    {'name': 'air bike', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/air bike.gif'},
    {'name': 'alternate heel touchers', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/alternate heel touchers.gif'},
    {'name': 'bottoms-up', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bottoms-up.gif'},
    {'name': 'cocoons', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/cocoons.gif'},
    {'name': 'cross body crunch', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/cross body crunch.gif'},
    {'name': 'crunch (hands overhead)', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/crunch (hands overhead).gif'},
    {'name': 'crunch floor', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/crunch floor.gif'},
    {'name': 'dead bug', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/dead bug.gif'},
    {'name': 'elbow-to-knee', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/elbow-to-knee.gif'},
    {'name': 'flexion leg sit up (bent knee)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/flexion leg sit up (bent knee).gif'},
    {'name': 'flexion leg sit up (straight arm)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/flexion leg sit up (straight arm).gif'},
    {'name': 'front plank with twist', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/front plank with twist.gif'},
    {'name': 'groin crunch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/groin crunch.gif'},
    {'name': 'hip raise (bent knee)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/hip raise (bent knee).gif'},
    {'name': 'jackknife sit-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.75, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/jackknife sit-up.gif'},
    {'name': 'janda sit-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.75, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/janda sit-up.gif'},
    {'name': 'oblique crunches floor', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/oblique crunches floor.gif'},
    {'name': 'push-up to side plank', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/push-up to side plank.gif'},
    {'name': 'russian twist', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/russian twist.gif'},
    {'name': 'seated side crunch (wall)', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/seated side crunch (wall).gif'},
    {'name': 'side bridge v. 2', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/side bridge v. 2.gif'},
    {'name': 'sit-up v. 2', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/sit-up v. 2.gif'},
    {'name': 'butt-ups', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/butt-ups.gif'},
    {'name': 'tuck crunch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/tuck crunch.gif'},
    {'name': 'reverse crunch', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/reverse crunch.gif'},
    {'name': 'crab twist toe touch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/crab twist toe touch.gif'},
    {'name': 'inchworm', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/inchworm.gif'},
    {'name': 'posterior step to overhead reach', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/posterior step to overhead reach.gif'},
    {'name': 'lunge with twist', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/lunge with twist.gif'},
    {'name': 'lying elbow to knee', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/lying elbow to knee.gif'},
    {'name': 'spine twist', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/spine twist.gif'},
    {'name': 'frog crunch', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/frog crunch.gif'},
    {'name': 'bridge - mountain climber (cross body)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/bridge - mountain climber (cross body).gif'},
    {'name': 'curl-up', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/curl-up.gif'},
    {'name': 'pelvic tilt', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/pelvic tilt.gif'},
    {'name': 'potty squat', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/potty squat.gif'},
    {'name': 'quarter sit-up', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/quarter sit-up.gif'},
    {'name': 'knee touch crunch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00, 'gifPath': 'assets/exercaiGif/knee touch crunch.gif'},
  ]
};