final Map<String, List<Map<String, dynamic>>> allExercises = {
  'back': [
    {'name': 'seated lower back stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'standing lateral stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'kneeling lat stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'lower back curl', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'one arm against wall', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'side lying floor stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'sphinx', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'spine stretch', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'standing pelvic tilt', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'upper back stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'upward facing dog', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'two toe touch (male)', 'baseSetsReps': 1, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
  ],

  'chest': [
    {'name': 'clock push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.3, 'baseCalories': 0.00},
    {'name': 'decline push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.35, 'baseCalories': 0.00},
    {'name': 'incline push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.35, 'baseCalories': 0.00},
    {'name': 'isometric wipers', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.02, 'baseCalories': 0.00},
    {'name': 'push-up (wall)', 'baseSetsReps': 2, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'shoulder tap push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'dynamic chest stretch (male)', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.02, 'baseCalories': 0.00},
    {'name': 'isometric chest squeeze', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.02, 'baseCalories': 0.00},
    {'name': 'wide hand push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'push and pull bodyweight', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'kneeling push-up (male)', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.35, 'baseCalories': 0.00},
    {'name': 'archer push-up', 'baseSetsReps': 1, 'baseReps': 10, 'burnCalperRep': 0.5, 'baseCalories': 0.00},
  ],

  'cardio': [
    {'name': 'mountain climber', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'run', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'burpee', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.5, 'baseCalories': 0.00},
    {'name': 'astride jumps (male)', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'half knee bends (male)', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'semi squat jump (male)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'star jump (male)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'skater hops', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'high knee against wall', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'push to run', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
  ],

  'lower arms':[
    {'name': 'side wrist pull stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'modified push up to lower arms', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'wrist circles', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
  ],
  'lower legs': [
    {'name': 'circles knee stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'ankle circles', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.4, 'baseCalories': 0.00},
    {'name': 'bodyweight standing calf raise', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.5, 'baseCalories': 0.00},
    {'name': 'calf stretch with hands against wall', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'one leg floor calf raise', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.5, 'baseCalories': 0.00},
    {'name': 'standing calves', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.5, 'baseCalories': 0.00},
    {'name': 'calf push stretch with hands against wall', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'standing calf raise (on a staircase)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.5, 'baseCalories': 0.00},
  ],

  'neck': [
    {'name': 'side push neck stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'neck side stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
  ],
  'shoulders': [
    {'name': 'rear deltoid stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'left hook. boxing', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
  ],
  'upper arms': [
    {'name': 'body-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'close-grip push-up', 'baseSetsReps': 3, 'baseReps': 8, 'burnCalperRep': 0.75, 'baseCalories': 0.00},
    {'name': 'diamond push-up', 'baseSetsReps': 3, 'baseReps': 6, 'burnCalperRep': 0.8, 'baseCalories': 0.00},
    {'name': 'overhead triceps stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'reverse dip', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'side push-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'triceps dips floor', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'triceps stretch', 'baseSetsSecs': 1, 'baseSecs': 15, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'push-up on lower arms', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'bodyweight side lying biceps curl', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'biceps leg concentration curl', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'bodyweight kneeling triceps extension', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'close-grip push-up (on knees)', 'baseSetsReps': 3, 'baseReps': 8, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'bench dip (knees bent)', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
  ],

  'upper legs': [
    {'name': 'jump squat', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.8, 'baseCalories': 0.00},
    {'name': 'kick out sit', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'lying (side) quads stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'march sit (wall)', 'baseSetsSecs': 1, 'baseSecs': 30, 'burnCalperSec': 0.1, 'baseCalories': 0.00},
    {'name': 'rear decline bridge', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'side hip abduction', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'single leg platform slide', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'standing single leg curl', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'hug knees to chest', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'iron cross stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'pelvic tilt into bridge', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'seated glute stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'straight leg outer hip abductor', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'walking lunge', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'twist hip lift', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'forward jump', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.85, 'baseCalories': 0.00},
    {'name': 'backward jump', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.85, 'baseCalories': 0.00},
    {'name': 'butterfly yoga pose', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'hamstring stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'all fours squat stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'leg up hamstring stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'runners stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'seated wide angle pose sequence', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'world greatest stretch', 'baseSetsSecs': 1, 'baseSecs': 20, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'squat to overhead reach', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.75, 'baseCalories': 0.00},
    {'name': 'side bridge hip abduction', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'split squats', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.75, 'baseCalories': 0.00},
    {'name': 'bodyweight drop jump squat', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.85, 'baseCalories': 0.00},
    {'name': 'quick feet v. 2', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.1, 'baseCalories': 0.00},
    {'name': 'lunge with jump', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.85, 'baseCalories': 0.00},
  ],

  'waist': [
    {'name': '3/4 sit-up', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'air bike', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'alternate heel touchers', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'bottoms-up', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'cocoons', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'cross body crunch', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'crunch (hands overhead)', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'crunch floor', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'dead bug', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'elbow-to-knee', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'flexion leg sit up (bent knee)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'flexion leg sit up (straight arm)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'front plank with twist', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'groin crunch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'hip raise (bent knee)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'jackknife sit-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.75, 'baseCalories': 0.00},
    {'name': 'janda sit-up', 'baseSetsReps': 3, 'baseReps': 10, 'burnCalperRep': 0.75, 'baseCalories': 0.00},
    {'name': 'oblique crunches floor', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'push-up to side plank', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'russian twist', 'baseSetsReps': 3, 'baseReps': 20, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'seated side crunch (wall)', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'side bridge v. 2', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'sit-up v. 2', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'butt-ups', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'tuck crunch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'reverse crunch', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'crab twist toe touch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'inchworm', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'posterior step to overhead reach', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'lunge with twist', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'lying elbow to knee', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.65, 'baseCalories': 0.00},
    {'name': 'spine twist', 'baseSetsSecs': 3, 'baseSecs': 30, 'burnCalperSec': 0.05, 'baseCalories': 0.00},
    {'name': 'frog crunch', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'bridge - mountain climber (cross body)', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'curl-up', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'pelvic tilt', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'potty squat', 'baseSetsReps': 3, 'baseReps': 12, 'burnCalperRep': 0.7, 'baseCalories': 0.00},
    {'name': 'quarter sit-up', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
    {'name': 'knee touch crunch', 'baseSetsReps': 3, 'baseReps': 15, 'burnCalperRep': 0.6, 'baseCalories': 0.00},
  ]

};